version: 0.1.{build}
image: Visual Studio 2022

configuration: Release

init:
- ps: Update-AppveyorBuild -Version "0.1.$env:appveyor_build_number+sha.$($env:appveyor_repo_commit.substring(0,7))"

nuget:
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '0.1.{build}.0'
  file_version: '0.1.{build}.0'
  informational_version: '{version}'

matrix:
  fast_finish: true # fail fast!

clone_depth: 1

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore src\DotJEM.NUnit3.sln # Restores .NET Framework (For Test Project)

build:
  project: src\DotJEM.NUnit3.sln
  publish_nuget: true
  publish_nuget_symbols: true

on_success:
- curl -s -o copilot https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot

deploy:
  provider: NuGet
  api_key:
    secure: PM9RVS7IEdZhY1gCjpIQ+gZWjwph2TmPMiQ3PvGKMJ3VL9EiGp9fZEEhFbCigiNq
  skip_symbols: true
  on:
    branch: master 
