name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Calculate Version Parameters
      id: version
      run: |
        build=${{github.run_number}}
        template=`cat ./VERSION`
        shortsha=$(git rev-parse --short ${{ github.sha }})
        echo "template=$template" >> $GITHUB_OUTPUT 
        echo "template=$template"
        echo "shortsha=$shortsha" >> $GITHUB_OUTPUT
        echo "shortsha=$shortsha"
        echo "semver=${template//build/$build}+sha.$shortsha" >> $GITHUB_OUTPUT
        echo "semver=${template//build/$build}+sha.$shortsha"
        echo "msver=${template//build/$build}.0" >> $GITHUB_OUTPUT
        echo "msver=${template//build/$build}.0"      
    
    # Starting the SQL Server here so that it has time to get up and running before we get to the tests, it seems doing this before the restore and build
    # is consistent enough.
    - name: Restore dependencies
      run: dotnet restore src/DotJEM.NUnit3.sln
      
    - name: Build
      working-directory: ./src
      run: > 
        dotnet build --configuration Release --no-restore 
        /p:Version=${{steps.version.outputs.semver}}
        /p:PackageVersion=${{steps.version.outputs.semver}}
        /p:AssemblyVersion=${{steps.version.outputs.msver}}
        /p:FileVersion=${{steps.version.outputs.msver}}
    
    - name: Test
      working-directory: ./src
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish
      if: github.event_name == 'push'
      working-directory: ./src
      run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate 
